server.port=${PORT:8080}

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Custom file storage directory
file.upload-dir=${UPLOAD_DIR:uploads}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://admin:admin@musicbox.nlgmhuq.mongodb.net/LocalBrandOnlineStore?retryWrites=true&w=majority}

# Spring Mail Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:huytn593@gmail.com}
spring.mail.password=${MAIL_PASSWORD:helt huip csus vvys}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}

# OpenAPI Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Ensure Spring Data MongoDB creates indexes automatically
spring.data.mongodb.auto-index-creation=true

# VNPAY Configuration
vnpay.tmnCode=${VNPAY_TMN_CODE:Z2JGT4AM}
vnpay.hashSecret=${VNPAY_HASH_SECRET:NGYTT28XP6HY978QRPGCZ2AJH76AWGJ9}
vnpay.url=${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.returnUrl=${VNPAY_RETURN_URL:http://localhost:8080/api/payment/vnpay_return}
vnpay.frontendReturnUrl=${VNPAY_FRONTEND_RETURN_URL:http://localhost:5173/payment-result}