package com.localbrand.service;

import com.localbrand.dto.ProductRequest;
import com.localbrand.exception.ResourceNotFoundException;
import com.localbrand.model.Category;
import com.localbrand.model.Product;
import com.localbrand.repository.CategoryRepository;
import com.localbrand.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
@RequiredArgsConstructor
@SuppressWarnings("null")
public class ProductService {

    private final ProductRepository productRepository;
    private final CategoryRepository categoryRepository;

    public Page<Product> getAllProducts(String search, String categoryId, Double minPrice, Double maxPrice, Pageable pageable) {
        boolean hasSearch = search != null && !search.isEmpty();
        boolean hasCategory = categoryId != null && !categoryId.isEmpty();
        boolean hasPriceFilter = minPrice != null || maxPrice != null;

        // Normalize min max prices
        double finalMinPrice = minPrice != null ? minPrice : 0;
        double finalMaxPrice = maxPrice != null ? maxPrice : Double.MAX_VALUE;

        // Let's implement combinations, though ideally one might use MongoTemplate Criteria for fully dynamic query
        
        if (hasSearch && hasCategory) {
            // we omit price filter here to keep the query generated by repos simple based on user's exact requirements, 
            // but in real world a custom Criteria builder would be used if multiple filters apply simultaneously
            return productRepository.findByTextSearchAndCategory(search, categoryId, pageable);
        } else if (hasSearch) {
            return productRepository.findByTextSearch(search, pageable);
        } else if (hasCategory && hasPriceFilter) {
            return productRepository.findByCategoryIdAndPriceBetween(categoryId, finalMinPrice, finalMaxPrice, pageable);
        } else if (hasCategory) {
            return productRepository.findByCategory(categoryId, pageable);
        } else if (hasPriceFilter) {
            return productRepository.findByPriceBetween(finalMinPrice, finalMaxPrice, pageable);
        } else {
            return productRepository.findAll(pageable);
        }
    }

    public Product getProductById(String id) {
        return productRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Product not found with id: " + id));
    }

    public Product createProduct(ProductRequest productRequest) {
        if (productRequest.getPrice() <= 0) {
            throw new com.localbrand.exception.BadRequestException("Giá sản phẩm phải lớn hơn 0");
        }

        Category category = categoryRepository.findById(productRequest.getCategoryId())
                .orElseThrow(() -> new ResourceNotFoundException("Category not found with id: " + productRequest.getCategoryId()));

        Product product = Product.builder()
                .name(productRequest.getName())
                .description(productRequest.getDescription())
                .price(productRequest.getPrice())
                .stock(productRequest.getStock())
                .categoryId(productRequest.getCategoryId())
                .categoryName(category.getName())
                .images(productRequest.getImages())
                .ratingAverage(0.0)
                .ratingCount(0)
                .createdAt(LocalDateTime.now())
                .build();

        return productRepository.save(product);
    }

    public Product updateProduct(String id, ProductRequest productRequest) {
        if (productRequest.getPrice() <= 0) {
            throw new com.localbrand.exception.BadRequestException("Giá sản phẩm phải lớn hơn 0");
        }

        Product existingProduct = getProductById(id);
        
        Category category = categoryRepository.findById(productRequest.getCategoryId())
                .orElseThrow(() -> new ResourceNotFoundException("Category not found with id: " + productRequest.getCategoryId()));

        existingProduct.setName(productRequest.getName());
        existingProduct.setDescription(productRequest.getDescription());
        existingProduct.setPrice(productRequest.getPrice());
        existingProduct.setStock(productRequest.getStock());
        existingProduct.setCategoryId(productRequest.getCategoryId());
        existingProduct.setCategoryName(category.getName());
        
        // Preserve old images if the updated request doesn't provide any, or just overwrite according to requirements
        if (productRequest.getImages() != null && !productRequest.getImages().isEmpty()) {
            existingProduct.setImages(productRequest.getImages());
        }
        
        existingProduct.setUpdatedAt(LocalDateTime.now());

        return productRepository.save(existingProduct);
    }

    public void deleteProduct(String id) {
        Product existingProduct = getProductById(id);
        productRepository.delete(existingProduct);
    }
}
